### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by dawnerd**
Boy is this a big change. Still a few things left, but I wanted to get some feedback on it.

It'll probably be easier to look right at the code instead of the diff since so much changed.

The core lives in `/lib` with the parsers nicely split up in `lib/parsers`.

The basic parser basically changed the same but the others are complete re-writes. Some tests are in, but there's some crucial ones I still need to add.

PS: keys in the test are throwaways and will be revoked soon enough.

### CODE REVIEW

**Comment by jgallen23** [comment]
Here's some feedback:

* SiteInfo should be instantiated with config values and then you should, separately call `siteinfo.parse(url, cb)` (or whatever).  That way you only need to pass config options once.
* why was CHANGELOG.md removed?
* I see some mentions of defaulting back to base parser if the smart parser fails, but I don't see that in code.  Can you point me to it?

**Comment by jgallen23** [comment]
this is so much cleaner btw!

**Comment by dawnerd** [comment]
- `siteinfo.parse()` is a perfect idea, will add that.
- Guess it was removed in my crazy cleanup. Do we find value in keeping them around instead of using the github releases?
- Didn't get the fallbacks in there. What will happen when I put them in is instead of the parser class calling `this.cb` it'll call a verify method that will check if data is returned correctly and if not call the basic parser.

**Comment by jgallen23** [comment]
any updates on the feedback?

**Comment by dawnerd** [comment]
Oh shoot, I forgot about those. I'll do them tonight.

**Pull request merged**
